# Generated by Django 5.1.3 on 2024-12-02 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analysis', '0005_supplierproduct_selling_price_per_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='selling_price_per_unit',
            new_name='our_selling_price_per_unit',
        ),
    ]
