# Generated by Django 5.1.2 on 2024-12-02 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analysis', '0006_rename_selling_price_per_unit_sale_our_selling_price_per_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierproduct',
            old_name='stock_quantity',
            new_name='quantity_supplied',
        ),
    ]
