# Generated by Django 5.1.2 on 2024-12-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analysis', '0008_rename_quantity_supplied_supplierproduct_stock_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierproduct',
            name='initial_stock_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
