# Generated by Django 5.1.2 on 2024-12-03 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analysis', '0009_supplierproduct_initial_stock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierproduct',
            name='initial_stock_quantity',
        ),
    ]
