# Generated by Django 5.1.3 on 2024-12-08 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analysis', '0012_sellingpricelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_selling_price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('supplier_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_analysis.supplierproduct')),
            ],
        ),
        migrations.DeleteModel(
            name='SellingPriceList',
        ),
    ]
