# Generated by Django 5.1.3 on 2024-12-10 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analysis', '0013_sellingprice_delete_sellingpricelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sale',
            name='supplier_product',
        ),
        migrations.RemoveField(
            model_name='sellingprice',
            name='supplier_product',
        ),
        migrations.RemoveField(
            model_name='supplierproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='supplierproduct',
            name='name',
        ),
        migrations.RemoveField(
            model_name='supplierproduct',
            name='selling_price_per_unit',
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, default='Unknown Customer', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='our_selling_price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_analysis.product'),
        ),
        migrations.AddField(
            model_name='sellingprice',
            name='product',
            field=models.OneToOneField(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_analysis.product'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_analysis.product'),
        ),
    ]
