# Generated by Django 5.1.3 on 2024-12-10 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_analysis', '0014_product_remove_sale_supplier_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.RemoveField(
            model_name='supplierproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sellingprice',
            name='product',
        ),
        migrations.AddField(
            model_name='sale',
            name='supplier_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_analysis.supplierproduct'),
        ),
        migrations.AddField(
            model_name='sellingprice',
            name='supplier_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_analysis.supplierproduct'),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='name',
            field=models.CharField(default='Unknown Product', max_length=100),
        ),
        migrations.AddField(
            model_name='supplierproduct',
            name='selling_price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, default='Unknown Customers', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='our_selling_price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock_analysis.supplier'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
